spring:
  application:
    name: aep-mongo-java-2026
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:Mongo@localhost:27018/linguagens?authSource=admin}

springdoc:
  swagger-ui:
    # URL curta para a documentação visual e interativa da API.
    path: /docs
    operations-sorter: method
